// ADRA Official Brand Colors — Graphic Standards Manual (PMS 335C primary)
export const C = {
  green:      "#007B5F",
  greenDark:  "#005A45",
  greenLight: "#E6F2EE",
  greenMid:   "#B3D9CE",
  grey:       "#54585A",
  greyLight:  "#F7F9F8",
  greyBorder: "#D8D8D8",
  white:      "#FFFFFF",
  black:      "#1C1C1C",
  errorBg:    "#FDECEA",
  errorText:  "#C0392B",
};

// Web fonts per brand guide p.26: Montserrat (headlines) + Zilla Slab (body)
export const F = {
  head: "'Montserrat', sans-serif",
  body: "'Zilla Slab', serif",
};

export const shared = {
  inputBase: {
    width: "100%",
    boxSizing: "border-box",
    padding: "10px 13px",
    border: `1px solid ${C.greyBorder}`,
    borderRadius: 4,
    fontFamily: F.body,
    fontSize: 14,
    color: C.black,
    outline: "none",
    background: C.white,
    lineHeight: 1.5,
  },
  card: {
    background: C.white,
    border: `1px solid ${C.greyBorder}`,
    borderRadius: 6,
    padding: "26px 30px",
    marginBottom: 22,
    boxShadow: "0 1px 4px rgba(0,0,0,0.05)",
  },
  btnGreen: {
    background: C.green,
    color: "#fff",
    border: "none",
    borderRadius: 4,
    padding: "11px 24px",
    fontFamily: F.head,
    fontWeight: 700,
    fontSize: 13,
    cursor: "pointer",
    letterSpacing: "0.02em",
  },
  btnOutline: {
    background: "transparent",
    color: C.green,
    border: `1.5px solid ${C.green}`,
    borderRadius: 4,
    padding: "9px 18px",
    fontFamily: F.head,
    fontWeight: 600,
    fontSize: 12,
    cursor: "pointer",
  },
  btnRed: {
    background: "transparent",
    color: "#b91c1c",
    border: "1px solid #f5c6c5",
    borderRadius: 4,
    padding: "6px 11px",
    fontFamily: F.head,
    fontSize: 11,
    cursor: "pointer",
  },
  fieldLabel: {
    display: "block",
    fontFamily: F.head,
    fontSize: 11,
    fontWeight: 700,
    color: C.grey,
    marginBottom: 5,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
  },
  tag: (type) => ({
    display: "inline-block",
    padding: "2px 9px",
    borderRadius: 2,
    fontSize: 10,
    fontFamily: F.head,
    fontWeight: 700,
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    background: type === "case_story" ? C.greenLight : type === "newsletter" ? "#EAF0FB" : "#FEF3E2",
    color:      type === "case_story" ? C.green      : type === "newsletter" ? "#2563EB" : "#B45309",
  }),
};
